// Classification of all state attributes possible
const stateAttrb = {
	// State object
	'Cancel current printing': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Cancel current printing',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'Emergency Stop': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Emergency Stop',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'total_duration': {
		root: 'printjob.time',
		rootName: 'Printjob Information - Time',
		name: 'Total Duration in seconds',
		read: true,
		write: false,
		role: 'value',
		unit: 'sec',
	},
	'progress': {
		root: 'printjob',
		rootName: 'Printjob Information',
		name: 'Progress in Percent',
		read: true,
		write: false,
		role: 'value',
		unit: '%',
	},
	'print_duration': {
		root: 'printjob.time',
		rootName: 'Printjob Information - Time',
		name: 'Time taken so far in seconds',
		read: true,
		write: false,
		role: 'value',
		unit: 'sec',
	'filament_used': {
		root: 'printjob',
		rootName: 'Printjob Information',
		name: 'Filament used in mm',
		read: true,
		write: false,
		role: 'value',
		unit: 'mm',
	},
	'filename': {
		root: 'printjob',
		rootName: 'Printjob Information',
		name: 'Filename of the Print',
		read: true,
		write: false,
		role: 'value',
		unit: 'mm',
	},
	'hostname': {
		root: 'Host',
		rootName: 'Host Information',
		name: 'Hostname',
		read: true,
		write: false,
		role: 'string',
	},
	'klippy_connected': {
		root: 'server',
		rootName: 'Server Information',
		name: 'klippy connected',
		type: 'boolean',
		read: true,
		write: false,
		role: 'indicator.connected',
	},
	'klippy_state': {
		root: 'server',
		rootName: 'Server Information',
		name: 'klippy state',
		type: 'string',
		read: true,
		write: false,
		role: 'indicator.working',
	},
	'Pause current printing': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Pause current printing',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'plugins': {
		root: 'server',
		rootName: 'Server Information',
		name: 'installed plugins',
		type: 'string',
		read: true,
		write: false,
		role: 'indicator.working',
	},
	'Reboot the system': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Reboot the system',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'Restart Firmware': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Restart Firmware',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'Restart Host': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Restart Host',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'Restart Server': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Restart Server',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'Resume current printing': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Resume current printing',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'Run gcode': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Run gcode, be carefully !',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'Shutdown the system': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Shutdown the system',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
};

module.exports = stateAttrb;
