/**
 * Object definitions can contain these elements to be called by stateSetCreate function, if not set default values are used
	'Cancel current printing': {			// id of state (name) submitted by stateSetCreate function
		root: '_Info',						// {default: NotUsed} Upper channel root
		rootName: 'Device Info channel,		// {default: NotUsed} Upper channel name
		name: 'Name of state',				// {default: same as id} Name definition for object
		type: >typeof (value)<,				// {default: typeof (value)} type of value automatically detected
		read: true,							// {default: true} Name defition for object
		write: true,						// {default: false} Name defition for object
		role: 'indicator.info',				// {default: state} Role as defined by https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md
		round_1: true,						// {default: NotUsed} Executed rounding function to 1 digit
		round_2: true,						// {default: NotUsed} Executed rounding function to 1 digit
		round_3: true,						// {default: NotUsed} Executed rounding function to 1 digit
	},
 */

const stateAttrb = {
	// State object
	'Cancel current printing': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Cancel current printing',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'Emergency Stop': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Emergency Stop',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'total_duration': {
		root: 'printjob.time',
		rootName: 'Printjob Information - Time',
		name: 'Total Duration in seconds',
		read: true,
		write: false,
		role: 'value',
		unit: 'sec',
	},
	'progress': {
		root: 'printjob',
		rootName: 'Printjob Information',
		name: 'Progress in Percent',
		read: true,
		write: false,
		role: 'value',
		unit: '%',
	},
	'print_duration': {
		root: 'printjob.time',
		rootName: 'Printjob Information - Time',
		name: 'Time taken so far in seconds',
		read: true,
		write: false,
		role: 'value',
		unit: 'sec',
	},
	'filament_used': {
		root: 'printjob',
		rootName: 'Printjob Information',
		name: 'Filament used in mm',
		read: true,
		write: false,
		role: 'value',
		unit: 'mm',
	},
	'filename': {
		root: 'printjob',
		rootName: 'Printjob Information',
		name: 'Filename of the Print',
		read: true,
		write: false,
		role: 'value',
	},
	'file_position': {
		root: 'printjob',
		rootName: 'Printjob Information',
		name: 'File Position in kb',
		read: true,
		write: false,
		role: 'value',
		unit: 'kb',
	},
	'state': {
		root: 'printjob',
		rootName: 'Printjob Information',
		name: 'Status of Printer',
		read: true,
		write: false,
		role: 'string',
	},
	'state_message': {
		root: 'printjob',
		rootName: 'Printjob Information',
		name: 'Statustext of Printer',
		read: true,
		write: false,
		role: 'string',
	},
	'klipper_path': {
		root: 'host.path',
		rootName: 'Host Information - Path of Files',
		name: 'Klipper Path',
		read: true,
		write: false,
		role: 'string',
	},
	'config_file': {
		root: 'host.path',
		rootName: 'Host Information - Path of Files',
		name: 'Klipper Config Path',
		read: true,
		write: false,
		role: 'string',
	},
	'log_file': {
		root: 'host.path',
		rootName: 'Host Information - Path of Files',
		name: 'Klipper Log Path',
		read: true,
		write: false,
		role: 'string',
	},
	'python_path': {
		root: 'host.path',
		rootName: 'Host Information - Path of Files',
		name: 'Python Path',
		read: true,
		write: false,
		role: 'string',
	},
	'hostname': {
		root: 'host',
		rootName: 'Host Information',
		name: 'Hostname',
		read: true,
		write: false,
		role: 'string',
	},
	'eventtime': {
		root: 'host',
		rootName: 'Host Information',
		name: 'Uptime in seconds',
		read: true,
		write: false,
		role: 'value',
		unit: 'sec',
	},
	'software_version': {
		root: 'host',
		rootName: 'Host Information',
		name: 'Klipper Version',
		read: true,
		write: false,
		role: 'string',
	},
	'cpu_info': {
		root: 'host',
		rootName: 'Host Information',
		name: 'Information about CPU',
		read: true,
		write: false,
		role: 'string',
	},
	'klippy_connected': {
		root: 'server',
		rootName: 'Server Information',
		name: 'klippy connected',
		type: 'boolean',
		read: true,
		write: false,
		role: 'indicator.connected',
	},
	'klippy_state': {
		root: 'server',
		rootName: 'Server Information',
		name: 'klippy state',
		type: 'string',
		read: true,
		write: false,
		role: 'indicator.working',
	},
	'Pause current printing': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Pause current printing',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'plugins': {
		root: 'server',
		rootName: 'Server Information',
		name: 'installed plugins',
		type: 'string',
		read: true,
		write: false,
		role: 'indicator.working',
	},
	'Reboot the system': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Reboot the system',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'Restart Firmware': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Restart Firmware',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'Restart Host': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Restart Host',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'Restart Server': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Restart Server',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'Resume current printing': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Resume current printing',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'Run gcode': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Run gcode, be carefully !',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'Shutdown the system': {
		root: 'control',
		rootName: 'Control Klipper',
		name: 'Shutdown the system',
		type: 'boolean',
		read: true,
		write: true,
		role: 'button',
	},
	'mesh_matrix': {
		name: 'Bed Mesh Values',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'mesh_max': {
		name: 'Bed Mesh Max Position',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'mesh_min': {
		name: 'Bed Mesh Min Position',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'probed_matrix': {
		name: 'Bed Mesh Values which are from your Bed Probe',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'profile_name': {
		name: 'Profile Name',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'fade_start': {
		name: 'Fade Start',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'horizontal_move_z': {
		name: 'Horizontal Movement for Z at the Probe',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'save_config_pending': {
		name: 'Status about the Save Config pending',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'power': {
		name: 'Power',
		type: 'number',
		read: true,
		write: false,
		role: 'value',
	},
	'pressure_advance': {
		name: 'Your Pressure Advanced Value',
		type: 'number',
		read: true,
		write: false,
		role: 'value',
	},
	'smooth_time': {
		name: 'Your Smooth Time Value',
		type: 'number',
		read: true,
		write: false,
		role: 'value',
	},
	'target': {
		name: 'Target',
		type: 'number',
		read: true,
		write: false,
		role: 'value',
	},
	'speed': {
		name: 'Speed',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'absolute_coordinates': {
		name: 'Absolute Coordinates',
		type: 'string',
		read: true,
		write: false,
		role: 'switch',
	},
	'absolute_extrude': {
		name: 'Absolute Extrude',
		type: 'string',
		read: true,
		write: false,
		role: 'switch',
	},
	'extrude_factor': {
		name: 'Your Extrude Factor',
		type: 'string',
		read: true,
		write: false,
		role: 'value',
	},
	'gcode_position': {
		name: 'Actual G Code Position',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'homing_origin': {
		name: 'Homing Origin Position',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'position': {
		name: 'Actual Position',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'speed_factor': {
		name: 'Speed Factor',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'temperature': {
		name: 'Actual Temperature',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'available_heaters': {
		name: 'Available Heaters',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'available_sensors': {
		name: 'Available Sensors',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'printing_time': {
		name: 'Printing Time',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'cols': {
		name: 'Columns',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'rows': {
		name: 'Rows',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'running': {
		name: 'Running Status',
		type: 'string',
		read: true,
		write: false,
		role: 'switch',
	},
	'timeout': {
		name: 'Timeout',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'is_paused': {
		name: 'is Paused Status',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'last_query': {
		name: 'Last Query',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'axis_maximum': {
		name: 'Maximum Axis Values',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'axis_minimum': {
		name: 'Minimum Axis Values',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'estimated_print_time': {
		name: 'Estimated Print Time',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'extruder': {
		name: 'Extruder Name',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'homed_axes': {
		name: 'Homed Axes',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'max_accel': {
		name: 'Maximum Acceleration',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'max_accel_to_decel': {
		name: 'Maximum Acceleration to Deceleration',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'max_velocity': {
		name: 'Maximum Velocity',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'print_time': {
		name: 'Actual Print Time',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'square_corner_velocity': {
		name: 'Square Corner Velocity',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'is_active': {
		name: 'Is Active Status',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'mesh_pps': {
		name: 'Mesh Points',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'probe_count': {
		name: 'Probe Count',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'relative_reference_index': {
		name: 'Relative Refernce Index',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'algo': {
		name: 'Algorithmus',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'max_x': {
		name: 'Maximum X',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'max_y': {
		name: 'Maximum Y',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'mesh_x_pps': {
		name: 'Mesh X PPS',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'mesh_y_pps': {
		name: 'Mesh Y PPS',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'min_x': {
		name: 'Minimum X',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'min_y': {
		name: 'Minimum Y',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'point': {
		name: 'Points',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'tension': {
		name: 'Tension',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'x_count': {
		name: 'X Count',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'y_count': {
		name: 'Y Count',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'control_pin': {
		name: 'Control Pin',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'pin_move_time': {
		name: 'Pin Movement Time',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'sensor_pin': {
		name: 'Sensor Pin',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'x_offset': {
		name: 'X Offset Value',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'y_offset': {
		name: 'Y Offset Value',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'z_offset': {
		name: 'Z Offset Value',
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'aliases': {
		name: 'Aliases',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'click_pin': {
		name: 'Click Pin',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'cs_pin': {
		name: 'CS Pin',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'encoder_pins': {
		name: 'Encoder Pins',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'lcd_type': {
		name: 'LCD Display Type',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'sclk_pin': {
		name: 'SCLK Pin',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'sid_pin': {
		name: 'SID Pin',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'control': {
		name: 'Control',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'dir_pin': {
		name: 'DIR Pin',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'enable_pin': {
		name: 'Enable Pin',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'filament_diameter': {
		name: 'Filament Diameter',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'heater_pin': {
		name: 'Heater Pin',
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'max_extrude_only_distance': {
		name: 'Maximum Extrude Only Distance', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'max_temp': {
		name: 'Maximum Temperatur', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'min_temp': {
		name: 'Minimum Temperatur', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'nozzle_diameter': {
		name: 'Nozzle Diameter', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'pid_kd': {
		name: 'PID kd', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'pid_ki': {
		name: 'PID ki', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'pid_kp': {
		name: 'PID kp', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'sensor_type': {
		name: 'Sensor Type', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'step_distance': {
		name: 'Step Distance', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'step_pin': {
		name: 'Step Pin', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'pin': {
		name: 'Pin', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'gcode': {
		name: 'G Code', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'rename_existing': {
		name: 'Rename Existing', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'default_parameter_e': {
		name: 'Default Parameter E', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'default_parameter_x': {
		name: 'Default Parameter X', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'default_parameter_y': {
		name: 'Default Parameter Y', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'default_parameter_z': {
		name: 'Default Parameter Z', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'serial': {
		name: 'Serial', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'kinematics': {
		name: 'Kinematics', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'max_z_accel': {
		name: 'Maximum Z Acceleration', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'max_z_velocity': {
		name: 'Maximum Z Velocity', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'home_xy_position': {
		name: 'Homing Position of X & Y', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'z_hop': {
		name: 'Z Hop', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'z_hop_speed': {
		name: 'Z Hop Speed', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'endstop_pin': {
		name: 'Endstop Pin', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'homing_speed': {
		name: 'Homing Speed', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'position_endstop': {
		name: 'Endstop Position', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'position_max': {
		name: 'Maximum Position', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'uart_pin': {
		name: 'UART Pin', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'message': {
		name: 'Message', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'position_min': {
		name: 'Minimum Position', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'value': {
		name: 'Value', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'hold_current': {
		name: 'Hold Current', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'stealthchop_threshold': {
		name: 'Threshold', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'microsteps': {
		name: 'Microsteps', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'version': {
		name: 'Version', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'points': {
		name: 'Points', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'pins': {
		name: 'Pins', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'run_current': {
		name: 'Run Current', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'path': {
		name: 'Path', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'max_extrude_only_accel': {
		name: 'Max extrude only acceleration', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'pressure_advance_smooth_time': {
		name: 'Pressure Advance Smooth Time', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'instantaneous_corner_velocity': {
		name: 'Instantaneous Corner Velocity', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'max_extrude_only_velocity': {
		name: 'Max Extrude only velocity', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'max_extrude_cross_section': {
		name: 'Max Extrude cross section', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'rpm': {
		name: 'RPM', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'bytes_invalid': {
		name: 'Invalid Bytes', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'bytes_read': {
		name: 'Read Bytes', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'bytes_retransmit': {
		name: 'Retransmit Bytes', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'bytes_write': {
		name: 'Writen Bytes', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'freq': {
		name: 'Frequence', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'mcu_awake': {
		name: 'MCU Awake', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'mcu_task_avg': {
		name: 'Average MCU Task', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'mcu_task_stddev': {
		name: 'MCU Task stddev', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'ready_bytes': {
		name: 'Ready Bytes', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'receive_seq': {
		name: 'Receive Sequence', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'retransmit_seq': {
		name: 'Retransmited Sequence', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'rto': {
		name: 'RTO', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'rttvar': {
		name: 'RTTVAR', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'send_seq': {
		name: 'Send Sequence', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'srtt': {
		name: 'SRTT', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'stalled_bytes': {
		name: 'Stalled Bytes', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'BUS_PINS_spi1': {
		name: 'Bus Pins SPI1', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'BUS_PINS_spi2': {
		name: 'Bus Pins SPI2', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'BUS_PINS_spi3': {
		name: 'Bus Pins SPI3', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'BUS_PINS_i2c1': {
		name: 'Bus Pins I2C1', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'BUS_PINS_i2c2': {
		name: 'Bus Pins I2C2', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'CLOCK_FREQ': {
		name: 'Clock Frequence', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'MCU': {
		name: 'MCU', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'RESERVE_PINS_USB': {
		name: 'USB Pins', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'send_seq': {
		name: 'Send Sequence', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'STATS_SUMSQ_BASE': {
		name: 'STATS SUMSQ BASE', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'STEP_DELAY': {
		name: 'Step Delay', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'mcu_version': {
		name: 'MCU Version', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'mcu_build_versions': {
		name: 'MCU Build Version', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'algorithm': {
		name: 'Algorithmus', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'bicubic_tension': {
		name: 'Bicubic Tension', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'fade_end': {
		name: 'Fade End', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'lift_speed': {
		name: 'Lift Speed', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'pin_up_reports_not_triggered': {
		name: 'Pin Up Reports not Triggered', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'pin_up_touch_mode_reports_triggered': {
		name: 'Pin Up Touch Mode Reports', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'sample_retract_dist': {
		name: 'Sample Retract Distance', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'samples_result': {
		name: 'Sample Result', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'samples_tolerance': {
		name: 'Sample Tolerance', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'samples_tolerance_retries': {
		name: 'Sample Tolerance Retries', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'stow_on_each_sample': {
		name: 'Stow on each Sample', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'samples': {
		name: 'Samples', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'mcu': {
		name: 'MCU', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'display_group': {
		name: 'Display Group', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'encoder_fast_rate': {
		name: 'Encoder Fastrate', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'menu_reverse_navigation': {
		name: 'Menu Reverse Navigation', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'menu_root': {
		name: 'Menu Root', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'menu_timeout': {
		name: 'Menu Timeout', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'max_power': {
		name: 'Maximum Power', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'min_extrude_temp': {
		name: 'Minimum Extruder Temperatur', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'pid_integral_max': {
		name: 'PID Integral Max', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'pullup_resistor': {
		name: 'Pullup Resistor', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'pwm_cycle_time': {
		name: 'PWM Cycle Resistor', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'cycle_time': {
		name: 'Cycle Time', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'hardware_pwm': {
		name: 'Hardware PWM', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'kick_start_time': {
		name: 'Kickstart Time', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'off_below': {
		name: 'Off below', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'shutdown_speed': {
		name: 'Shutdown Speed', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'enable_force_mode': {
		name: 'Enable Force Mode', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'inline_resistor': {
		name: 'Inline Resistor', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'last_z_result': {
		name: 'Last Z-Result', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'INITIAL_PINS': {
		name: 'Initial Pins', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'max_error': {
		name: 'Maximum Error', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'hysteresis': {
		name: 'Hysteresis', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'heating_gain': {
		name: 'Heating Gain', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'check_gain_time': {
		name: 'Check Gain Time', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'driver_hend': {
		name: 'Driver Hend', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'driver_hstrt': {
		name: 'Driver HSTRT?', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'driver_iholddelay': {
		name: 'Driver Holddelay', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'driver_pwm_autograd': {
		name: 'Driver PWM Autograd', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'driver_pwm_autoscale': {
		name: 'Driver PWM Autoscale', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'driver_pwm_freq': {
		name: 'Driver PWM Frequence', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'driver_pwm_grad': {
		name: 'Driver PWM Grad', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'driver_pwm_lim': {
		name: 'Driver PWM Lim', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'driver_pwm_ofs': {
		name: 'Driver PWM Ofs', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'driver_pwm_reg': {
		name: 'Driver PWM Reg', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'driver_sgthrs': {
		name: 'Driver sgthrs', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'driver_tbl': {
		name: 'Driver Tbl', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'driver_toff': {
		name: 'Driver Toff', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'driver_tpowerdown': {
		name: 'Driver TPowerdown', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'uart_address': {
		name: 'UART Address', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'interpolate': {
		name: 'Interpolate', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'sense_resistor': {
		name: 'Sense Resistor', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'homing_retract_speed': {
		name: 'Homing Retract Speed', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'homing_speed': {
		name: 'Homing Speed', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'homing_retract_dist': {
		name: 'Homing Retract Distance', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'second_homing_speed': {
		name: 'Homing second Speed', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'move_to_previous': {
		name: 'Move to Previous', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'buffer_time_high': {
		name: 'Buffer Time High', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'buffer_time_low': {
		name: 'Buffer Time Low', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'buffer_time_start': {
		name: 'Buffer Time Start', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'move_flush_time': {
		name: 'Move Flushtime', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'recover_velocity': {
		name: 'Velocity Recover', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'pwm': {
		name: 'PWM', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'shutdown_value': {
		name: 'Shutdown Value', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'baud': {
		name: 'BAUD Rate', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'max_stepper_error': {
		name: 'Max Stepper Error', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'damping_ratio_y': {
		name: 'Damping Ratio Y', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'damping_ratio_x': {
		name: 'Damping Ratio X', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'shaper_type': {
		name: 'Shaper Type', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'shaper_type_y': {
		name: 'Shaper Type Y', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'shaper_type_x': {
		name: 'Shaper Type X', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'shaper_freq_y': {
		name: 'Shaper Frequence Y', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'shaper_freq_x': {
		name: 'Shaper Frequence X', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'move_check_distance': {
		name: 'Check Distance Move', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'split_delta_z': {
		name: 'Split Delta Z', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
	'probe_with_touch_mode': {
		name: 'Probe with Touchmode', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'enable_force_move': {
		name: 'Enable Force Move', 
		type: 'string',
		read: true,
		write: false,
		role: 'state',
	},
	'ADC_MAX': {
		name: 'ADC Maximum', 
		type: 'number',
		read: true,
		write: false,
		role: 'state',
	},
};

module.exports = stateAttrb;
